import { Lexend } from "next/font/google";
import "./globals.css";
import Navbar from "../../components/Navbar";

const lexend = Lexend({
  weight: ["300","400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="rootbg" lang="en">
      <body className={`${lexend.className} p-4 xl:p-8 2xl:p-10 rootbg`}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
